### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by ShaniGam** [transedward/pytorch-dqn#1]
How much time did the training take you on games such as pong and breakout?

**Comment by hungtuchen** [comment]
Sorry, I forgot the details. I remembered it takes almost 1m timesteps to see a considerable improvement on cumulative rewards. And it takes 1x hours to see the results close to paper. (But not as good as it, maybe we can see if there is anything to improve)

**Comment by hungtuchen** [comment]
If there is no further question, this issue would be closed.
