### ISSUE TITLE
Take a long time to converge

### ISSUE THREAD

**Issue by Ja1r0** [transedward/pytorch-dqn#9]
I run the code,and found your dqn algorithm take such a long time to converge.Actually,I found few implementation of dqn can converge in github.They can converge in a afternoon.I use a piece of GTX1080Ti.It is appreciate that your implementation can converge.But your code take a day and a night to converge.I don't know why.

**Comment by Unimax** [comment]
@Ja1r0 which environment did you tested on?
also if u did the experiment let me know does the converge stays or it starts falling apart again with further training.

default target update frequency seems too high and little larger batch size should help too.
